CREATE DATABASE blog;
USE blog;

CREATE TABLE posts (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

+++++++

ALTER TABLE posts ADD COLUMN image VARCHAR(255) DEFAULT NULL;
